import { Montserrat } from "next/font/google";
import "./globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Layout from "../components/layout";
import Script from "next/script";

config.autoAddCss = false;
const inter = Montserrat({ weights: 200, subsets: ["latin"] });

export const metadata = {
  title: "Nakula Sadewa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-JM6388BK6Z"></script>
      <Script id="google-analytics">
        {` window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
  
    gtag('config', 'G-JM6388BK6Z');`}
      </Script>
      <body className={inter.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
